package org.model.scheduler;
// Generated 26 Sep, 2018 8:49:36 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzFiredTriggers generated by hbm2java
 */
@Entity
@Table(name="qrtz_fired_triggers"
    ,catalog="USERMANAGER"
)
public class QrtzFiredTriggers  implements java.io.Serializable {


     private QrtzFiredTriggersId id;
     private String triggerName;
     private String triggerGroup;
     private String instanceName;
     private long firedTime;
     private long schedTime;
     private int priority;
     private String state;
     private String jobName;
     private String jobGroup;
     private String isNonconcurrent;
     private String requestsRecovery;

    public QrtzFiredTriggers() {
    }

	
    public QrtzFiredTriggers(QrtzFiredTriggersId id, String triggerName, String triggerGroup, String instanceName, long firedTime, long schedTime, int priority, String state) {
        this.id = id;
        this.triggerName = triggerName;
        this.triggerGroup = triggerGroup;
        this.instanceName = instanceName;
        this.firedTime = firedTime;
        this.schedTime = schedTime;
        this.priority = priority;
        this.state = state;
    }
    public QrtzFiredTriggers(QrtzFiredTriggersId id, String triggerName, String triggerGroup, String instanceName, long firedTime, long schedTime, int priority, String state, String jobName, String jobGroup, String isNonconcurrent, String requestsRecovery) {
       this.id = id;
       this.triggerName = triggerName;
       this.triggerGroup = triggerGroup;
       this.instanceName = instanceName;
       this.firedTime = firedTime;
       this.schedTime = schedTime;
       this.priority = priority;
       this.state = state;
       this.jobName = jobName;
       this.jobGroup = jobGroup;
       this.isNonconcurrent = isNonconcurrent;
       this.requestsRecovery = requestsRecovery;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="entryId", column=@Column(name="ENTRY_ID", nullable=false, length=95) ) } )
    public QrtzFiredTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzFiredTriggersId id) {
        this.id = id;
    }
    
    @Column(name="TRIGGER_NAME", nullable=false, length=200)
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }
    
    @Column(name="TRIGGER_GROUP", nullable=false, length=200)
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
    
    @Column(name="INSTANCE_NAME", nullable=false, length=200)
    public String getInstanceName() {
        return this.instanceName;
    }
    
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }
    
    @Column(name="FIRED_TIME", nullable=false)
    public long getFiredTime() {
        return this.firedTime;
    }
    
    public void setFiredTime(long firedTime) {
        this.firedTime = firedTime;
    }
    
    @Column(name="SCHED_TIME", nullable=false)
    public long getSchedTime() {
        return this.schedTime;
    }
    
    public void setSchedTime(long schedTime) {
        this.schedTime = schedTime;
    }
    
    @Column(name="PRIORITY", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    
    @Column(name="STATE", nullable=false, length=16)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="JOB_NAME", length=200)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    
    @Column(name="JOB_GROUP", length=200)
    public String getJobGroup() {
        return this.jobGroup;
    }
    
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }
    
    @Column(name="IS_NONCONCURRENT", length=1)
    public String getIsNonconcurrent() {
        return this.isNonconcurrent;
    }
    
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent;
    }
    
    @Column(name="REQUESTS_RECOVERY", length=1)
    public String getRequestsRecovery() {
        return this.requestsRecovery;
    }
    
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }




}


