package org.model.scheduler;
// Generated 26 Sep, 2018 8:49:36 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzSchedulerState generated by hbm2java
 */
@Entity
@Table(name="qrtz_scheduler_state"
    ,catalog="USERMANAGER"
)
public class QrtzSchedulerState  implements java.io.Serializable {


     private QrtzSchedulerStateId id;
     private long lastCheckinTime;
     private long checkinInterval;

    public QrtzSchedulerState() {
    }

    public QrtzSchedulerState(QrtzSchedulerStateId id, long lastCheckinTime, long checkinInterval) {
       this.id = id;
       this.lastCheckinTime = lastCheckinTime;
       this.checkinInterval = checkinInterval;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="instanceName", column=@Column(name="INSTANCE_NAME", nullable=false, length=200) ) } )
    public QrtzSchedulerStateId getId() {
        return this.id;
    }
    
    public void setId(QrtzSchedulerStateId id) {
        this.id = id;
    }
    
    @Column(name="LAST_CHECKIN_TIME", nullable=false)
    public long getLastCheckinTime() {
        return this.lastCheckinTime;
    }
    
    public void setLastCheckinTime(long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }
    
    @Column(name="CHECKIN_INTERVAL", nullable=false)
    public long getCheckinInterval() {
        return this.checkinInterval;
    }
    
    public void setCheckinInterval(long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }




}


