package org.model.util;
// Generated 2 Oct, 2018 11:19:34 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientdetails generated by hbm2java
 */
@Entity
@Table(name="clientdetails"
    ,catalog="USERMANAGER"
)
public class Clientdetails  implements java.io.Serializable {


     private String appId;
     private String resourceIds;
     private String appSecret;
     private String scope;
     private String grantTypes;
     private String redirectUrl;
     private String authorities;
     private Integer accessTokenValidity;
     private Integer refreshTokenValidity;
     private String additionalInformation;
     private String autoApproveScopes;

    public Clientdetails() {
    }

	
    public Clientdetails(String appId) {
        this.appId = appId;
    }
    public Clientdetails(String appId, String resourceIds, String appSecret, String scope, String grantTypes, String redirectUrl, String authorities, Integer accessTokenValidity, Integer refreshTokenValidity, String additionalInformation, String autoApproveScopes) {
       this.appId = appId;
       this.resourceIds = resourceIds;
       this.appSecret = appSecret;
       this.scope = scope;
       this.grantTypes = grantTypes;
       this.redirectUrl = redirectUrl;
       this.authorities = authorities;
       this.accessTokenValidity = accessTokenValidity;
       this.refreshTokenValidity = refreshTokenValidity;
       this.additionalInformation = additionalInformation;
       this.autoApproveScopes = autoApproveScopes;
    }
   
     @Id 
    
    @Column(name="appId", unique=true, nullable=false)
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }
    
    @Column(name="resourceIds")
    public String getResourceIds() {
        return this.resourceIds;
    }
    
    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds;
    }
    
    @Column(name="appSecret")
    public String getAppSecret() {
        return this.appSecret;
    }
    
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }
    
    @Column(name="scope")
    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }
    
    @Column(name="grantTypes")
    public String getGrantTypes() {
        return this.grantTypes;
    }
    
    public void setGrantTypes(String grantTypes) {
        this.grantTypes = grantTypes;
    }
    
    @Column(name="redirectUrl")
    public String getRedirectUrl() {
        return this.redirectUrl;
    }
    
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
    }
    
    @Column(name="authorities")
    public String getAuthorities() {
        return this.authorities;
    }
    
    public void setAuthorities(String authorities) {
        this.authorities = authorities;
    }
    
    @Column(name="access_token_validity")
    public Integer getAccessTokenValidity() {
        return this.accessTokenValidity;
    }
    
    public void setAccessTokenValidity(Integer accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity;
    }
    
    @Column(name="refresh_token_validity")
    public Integer getRefreshTokenValidity() {
        return this.refreshTokenValidity;
    }
    
    public void setRefreshTokenValidity(Integer refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity;
    }
    
    @Column(name="additionalInformation", length=4096)
    public String getAdditionalInformation() {
        return this.additionalInformation;
    }
    
    public void setAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation;
    }
    
    @Column(name="autoApproveScopes")
    public String getAutoApproveScopes() {
        return this.autoApproveScopes;
    }
    
    public void setAutoApproveScopes(String autoApproveScopes) {
        this.autoApproveScopes = autoApproveScopes;
    }




}


