package org.model.util;
// Generated 1 Oct, 2018 5:40:34 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OauthApprovalsId generated by hbm2java
 */
@Embeddable
public class OauthApprovalsId  implements java.io.Serializable {


     private String userId;
     private String clientId;
     private String scope;
     private String status;
     private Date expiresAt;
     private Date lastModifiedAt;

    public OauthApprovalsId() {
    }

	
    public OauthApprovalsId(Date expiresAt, Date lastModifiedAt) {
        this.expiresAt = expiresAt;
        this.lastModifiedAt = lastModifiedAt;
    }
    public OauthApprovalsId(String userId, String clientId, String scope, String status, Date expiresAt, Date lastModifiedAt) {
       this.userId = userId;
       this.clientId = clientId;
       this.scope = scope;
       this.status = status;
       this.expiresAt = expiresAt;
       this.lastModifiedAt = lastModifiedAt;
    }
   

    @Column(name="userId")
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name="clientId")
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    @Column(name="scope")
    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }

    @Column(name="status", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name="expiresAt", nullable=false, length=0)
    public Date getExpiresAt() {
        return this.expiresAt;
    }
    
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    @Column(name="lastModifiedAt", nullable=false, length=0)
    public Date getLastModifiedAt() {
        return this.lastModifiedAt;
    }
    
    public void setLastModifiedAt(Date lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OauthApprovalsId) ) return false;
		 OauthApprovalsId castOther = ( OauthApprovalsId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getClientId()==castOther.getClientId()) || ( this.getClientId()!=null && castOther.getClientId()!=null && this.getClientId().equals(castOther.getClientId()) ) )
 && ( (this.getScope()==castOther.getScope()) || ( this.getScope()!=null && castOther.getScope()!=null && this.getScope().equals(castOther.getScope()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getExpiresAt()==castOther.getExpiresAt()) || ( this.getExpiresAt()!=null && castOther.getExpiresAt()!=null && this.getExpiresAt().equals(castOther.getExpiresAt()) ) )
 && ( (this.getLastModifiedAt()==castOther.getLastModifiedAt()) || ( this.getLastModifiedAt()!=null && castOther.getLastModifiedAt()!=null && this.getLastModifiedAt().equals(castOther.getLastModifiedAt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getClientId() == null ? 0 : this.getClientId().hashCode() );
         result = 37 * result + ( getScope() == null ? 0 : this.getScope().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getExpiresAt() == null ? 0 : this.getExpiresAt().hashCode() );
         result = 37 * result + ( getLastModifiedAt() == null ? 0 : this.getLastModifiedAt().hashCode() );
         return result;
   }   


}


