package org.model.util;
// Generated 2 Oct, 2018 11:19:34 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzPausedTriggerGrps generated by hbm2java
 */
@Entity
@Table(name="qrtz_paused_trigger_grps"
    ,catalog="USERMANAGER"
)
public class QrtzPausedTriggerGrps  implements java.io.Serializable {


     private QrtzPausedTriggerGrpsId id;

    public QrtzPausedTriggerGrps() {
    }

    public QrtzPausedTriggerGrps(QrtzPausedTriggerGrpsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="triggerGroup", column=@Column(name="TRIGGER_GROUP", nullable=false, length=200) ) } )
    public QrtzPausedTriggerGrpsId getId() {
        return this.id;
    }
    
    public void setId(QrtzPausedTriggerGrpsId id) {
        this.id = id;
    }




}


