package org.model.util;
// Generated 2 Oct, 2018 11:19:34 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzSimpleTriggers generated by hbm2java
 */
@Entity
@Table(name="qrtz_simple_triggers"
    ,catalog="USERMANAGER"
)
public class QrtzSimpleTriggers  implements java.io.Serializable {


     private QrtzSimpleTriggersId id;
     private long repeatCount;
     private long repeatInterval;
     private long timesTriggered;

    public QrtzSimpleTriggers() {
    }

    public QrtzSimpleTriggers(QrtzSimpleTriggersId id, long repeatCount, long repeatInterval, long timesTriggered) {
       this.id = id;
       this.repeatCount = repeatCount;
       this.repeatInterval = repeatInterval;
       this.timesTriggered = timesTriggered;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="triggerName", column=@Column(name="TRIGGER_NAME", nullable=false, length=200) ), 
        @AttributeOverride(name="triggerGroup", column=@Column(name="TRIGGER_GROUP", nullable=false, length=200) ) } )
    public QrtzSimpleTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzSimpleTriggersId id) {
        this.id = id;
    }
    
    @Column(name="REPEAT_COUNT", nullable=false)
    public long getRepeatCount() {
        return this.repeatCount;
    }
    
    public void setRepeatCount(long repeatCount) {
        this.repeatCount = repeatCount;
    }
    
    @Column(name="REPEAT_INTERVAL", nullable=false)
    public long getRepeatInterval() {
        return this.repeatInterval;
    }
    
    public void setRepeatInterval(long repeatInterval) {
        this.repeatInterval = repeatInterval;
    }
    
    @Column(name="TIMES_TRIGGERED", nullable=false)
    public long getTimesTriggered() {
        return this.timesTriggered;
    }
    
    public void setTimesTriggered(long timesTriggered) {
        this.timesTriggered = timesTriggered;
    }




}


