package org.model.util;
// Generated 1 Oct, 2018 5:40:34 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzTriggers generated by hbm2java
 */
@Entity
@Table(name="qrtz_triggers"
    ,catalog="USERMANAGER"
)
public class QrtzTriggers  implements java.io.Serializable {


     private QrtzTriggersId id;
     private String jobName;
     private String jobGroup;
     private String description;
     private Long nextFireTime;
     private Long prevFireTime;
     private Integer priority;
     private String triggerState;
     private String triggerType;
     private long startTime;
     private Long endTime;
     private String calendarName;
     private Short misfireInstr;
     private byte[] jobData;

    public QrtzTriggers() {
    }

	
    public QrtzTriggers(QrtzTriggersId id, String jobName, String jobGroup, String triggerState, String triggerType, long startTime) {
        this.id = id;
        this.jobName = jobName;
        this.jobGroup = jobGroup;
        this.triggerState = triggerState;
        this.triggerType = triggerType;
        this.startTime = startTime;
    }
    public QrtzTriggers(QrtzTriggersId id, String jobName, String jobGroup, String description, Long nextFireTime, Long prevFireTime, Integer priority, String triggerState, String triggerType, long startTime, Long endTime, String calendarName, Short misfireInstr, byte[] jobData) {
       this.id = id;
       this.jobName = jobName;
       this.jobGroup = jobGroup;
       this.description = description;
       this.nextFireTime = nextFireTime;
       this.prevFireTime = prevFireTime;
       this.priority = priority;
       this.triggerState = triggerState;
       this.triggerType = triggerType;
       this.startTime = startTime;
       this.endTime = endTime;
       this.calendarName = calendarName;
       this.misfireInstr = misfireInstr;
       this.jobData = jobData;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="triggerName", column=@Column(name="TRIGGER_NAME", nullable=false, length=200) ), 
        @AttributeOverride(name="triggerGroup", column=@Column(name="TRIGGER_GROUP", nullable=false, length=200) ) } )
    public QrtzTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzTriggersId id) {
        this.id = id;
    }
    
    @Column(name="JOB_NAME", nullable=false, length=200)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    
    @Column(name="JOB_GROUP", nullable=false, length=200)
    public String getJobGroup() {
        return this.jobGroup;
    }
    
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }
    
    @Column(name="DESCRIPTION", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="NEXT_FIRE_TIME")
    public Long getNextFireTime() {
        return this.nextFireTime;
    }
    
    public void setNextFireTime(Long nextFireTime) {
        this.nextFireTime = nextFireTime;
    }
    
    @Column(name="PREV_FIRE_TIME")
    public Long getPrevFireTime() {
        return this.prevFireTime;
    }
    
    public void setPrevFireTime(Long prevFireTime) {
        this.prevFireTime = prevFireTime;
    }
    
    @Column(name="PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    
    @Column(name="TRIGGER_STATE", nullable=false, length=16)
    public String getTriggerState() {
        return this.triggerState;
    }
    
    public void setTriggerState(String triggerState) {
        this.triggerState = triggerState;
    }
    
    @Column(name="TRIGGER_TYPE", nullable=false, length=8)
    public String getTriggerType() {
        return this.triggerType;
    }
    
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }
    
    @Column(name="START_TIME", nullable=false)
    public long getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }
    
    @Column(name="END_TIME")
    public Long getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="CALENDAR_NAME", length=200)
    public String getCalendarName() {
        return this.calendarName;
    }
    
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }
    
    @Column(name="MISFIRE_INSTR")
    public Short getMisfireInstr() {
        return this.misfireInstr;
    }
    
    public void setMisfireInstr(Short misfireInstr) {
        this.misfireInstr = misfireInstr;
    }
    
    @Column(name="JOB_DATA")
    public byte[] getJobData() {
        return this.jobData;
    }
    
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }




}


